---
title: "Main - Adjusted for ANCOM-BC2"
author: "Orr Tobaly"
date: "2025-04-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading packages
```{r}
library(vegan)
library(ggpubr)
library(microbiome)
library(phyloseq)
library(qiime2R)
library(microeco)
library(dplyr)
library(tidyverse)
library(magrittr)
library(sva)
library(GUniFrac)
```

# Import data
```{r}
metadata <- read_q2metadata("00.metadata.combined.2020_2021.tsv")
taxa <- read_qza("taxonomy-dada2.qza")$data %>% parse_taxonomy()
feature_table <- as.data.frame(read_qza("table-dada2.qza")$data)
tree <- read_qza("rooted-tree-dada2.qza")$data

# Prepare the microeco dataset
rownames(metadata) <- metadata[,1]  # Set sample IDs as rownames
dataset <- microtable$new(sample_table = metadata, 
                          otu_table = feature_table, 
                          tax_table = taxa,
                          phylo_tree = tree)

rm(metadata, taxa, feature_table, tree)

# Data tidying
dataset$tidy_dataset()
dataset$tax_table %<>% base::subset(Kingdom == "Archaea" | Kingdom == "Bacteria")
dataset$filter_pollution(taxa = c("mitochondria", "chloroplast"))
```

# Batch effect
```{r}
# Calculate beta diversity
dataset$cal_betadiv(unifrac = TRUE)

# Function for beta ordination
create_beta_ordination <- function(dataset, 
                                  factor_name, 
                                  measure = "bray", 
                                  method = "PCoA",
                                  plot_type = c("point", "ellipse"),
                                  title = NULL,
                                  color_values = NULL) {
  
  # Create the trans_beta object
  beta_obj <- trans_beta$new(dataset = dataset, 
                             group = factor_name, 
                             measure = measure)
  
  # Run the ordination
  beta_obj$cal_ordination(method = method)
  
  # Generate the plot title if not provided
  if(is.null(title)) {
    title <- paste("Beta Diversity by", factor_name)
  }
  
  # Create the plot
  beta_plot <- beta_obj$plot_ordination(
    plot_type = plot_type,
    plot_color = factor_name,
    plot_shape = factor_name,
  ) + 
    labs(title = title)
  
  # Return both the object and the plot
  return(list(
    beta_object = beta_obj,
    plot = beta_plot
  ))
}

# Create ordination for year, batch, time, carriage status
ordinations <- list()
for (var in c("year", "batch", "time", "case_control")) {
  ordinations[[var]] <- create_beta_ordination(
    dataset = dataset,
    factor_name = var,
    title = paste0("Pre-correction - Batch Effect by ", var)
  )
}


```

